### ISSUE TITLE
Cert error when visiting goplay.space

### ISSUE THREAD

**Issue by mattgiltaji** [iafan/goplayspace#13]
I'm getting a NET::ERR_CERT_AUTHORITY_INVALID error when first accessing https://goplay.space/ in chrome 60.0.3112.90 (Official Build) (64-bit) on a windows 10 machine.  I get the same error in Firefox 53.0 (32-bit) and ssl labs says that this is due to a missing intermediate cert:

https://www.ssllabs.com/ssltest/analyze.html?d=goplay.space

There are workarounds available in the browsers now (add security exception, etc) but it's probably better to fix the certs in case the browsers block the workaround in later versions.

**Comment by iafan** [comment]
Thanks for reporting. I fixed the issue: https://www.ssllabs.com/ssltest/analyze.html?d=goplay.space&latest

Please reopen if you still have problems with the certificate.
