### ISSUE TITLE
Change cursor colour in night theme

### ISSUE THREAD

**Issue by nikitavoloboev** [iafan/goplayspace#14]
Since it's black, you can't see it in night theme : 

Like here : 

![](http://i.imgur.com/LqrXlm1.png )

You can barely see it.

**Comment by iafan** [comment]
The cursor color in the dark theme is set to white, though it seems there's a problem with rendering it in Safari. Do you use Safari as well?

**Comment by nikitavoloboev** [comment]
Yep, this is in Safari.

**Comment by iafan** [comment]
Should be fixed now. Reload the page and try again.
