### ISSUE TITLE
Help customizing

### ISSUE THREAD

**Issue by veganexe** [iafan/goplayspace#15]
Sorry for creating an issue for this, but how do I go about customizing goplayspace?
For example, 

- Changing app name to "Go" instead of "The Go Play Space"
- Removing the right window i.e, the "About Go Play Space"  window
- Changing theme default to Dark and removing all other themes.

**Comment by iafan** [comment]
I'd recommend looking at the code and commenting out or changing parts of the code related to the things you're interested in, for example:

App name:
- https://github.com/iafan/goplayspace/blob/master/static/index.html#L5
- https://github.com/iafan/goplayspace/blob/master/client/component/app/strings.go#L6

Right window:
- https://github.com/iafan/goplayspace/blob/master/client/component/app/app.go#L651-L672
- ... and related code ...

Theme:
- https://github.com/iafan/goplayspace/blob/master/client/component/app/app.go#L607 (change this to `"dark": true`)
- ...remove theme-related code...

**Comment by veganexe** [comment]
Wow, that was very fast. Thanks. However, just realized that by removing the window element I will lose the function help look-up feature. Is is possible, that the window pops out only when a function is highlighted, otherwise remains hidden?

**Comment by iafan** [comment]
I'd suggest to file a separate issue (feature request) for this.
