### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by veganexe** [iafan/goplayspace#16]
On a DO droplet, CentOS 7.3, Go 1.9
```

[root@123 tmp]# go get -u github.com/gopherjs/gopherjs
[root@123 tmp]# go get -u github.com/gopherjs/vecty
[root@123 tmp]# go get -u github.com/iafan/goplayspace/...
# github.com/iafan/goplayspace/client/component/log
/root/Projects/golang/src/github.com/iafan/goplayspace/client/component/log/log.go:34:29: undefined: vecty.MarkupOrComponentOrHTML
/root/Projects/golang/src/github.com/iafan/goplayspace/client/component/log/log.go:38:16: undefined: vecty.MarkupOrComponentOrHTML


[root@123 tmp]# cd $GOPATH/src/github.com/iafan/goplayspace/bin
[root@123 bin]# ./build-client && ./build-server
component/log/log.go:34:29: MarkupOrComponentOrHTML not declared by package vecty
component/log/log.go:38:16: MarkupOrComponentOrHTML not declared by package vecty
component/log/log.go:111:12: cannot use l.getEvents() (value of type []invalid type) as []github.com/gopherjs/vecty.MarkupOrChild value in argument to elem.Div
gzip: client.js: No such file or directory
gzip: client.js.map: No such file or directory


```

**Comment by iafan** [comment]
I believe this is due to [breaking changes](https://github.com/gopherjs/vecty/blob/master/doc/CHANGELOG.md#sept-2-2017-pr-134-major-breaking-change) introduced in Vecty a few days ago. Go Play Space wasn't updated yet to reflect those, so if you want to build one locally now, I'd recommend resetting Vecty manually to some prior commit before those breaking changes.

I plan to update Go Play Space to work with the new Vecty code, but PRs are welcome.

**Comment by veganexe** [comment]
**MarkupOrComponentOrHTML** has been renamed to **MarkupOrChild**, and now includes nil and the new List and MarkupList (instead of Markup, see below) types.

A rename will solve it?

**Comment by iafan** [comment]
I don't know, since I didn't look at the changes yet. Maybe other tweaks will be necessary as well. The safest bet would be to reset your local Vecty checkout in `$GOPATH/src/github.com/gopherjs/vecty` to some earlier commit (e.g. `7d15bbeaa9172b71e239a83098d29ffc3b70590b` — the one I currently have locally).

**Comment by veganexe** [comment]
```
go get -u github.com/gopherjs/gopherjs
go get -d github.com/gopherjs/vecty
cd $GOPATH/src/github.com/gopherjs/vecty
git checkout 7d15bbeaa9172b71e239a83098d29ffc3b70590b
go get github.com/gopherjs/vecty
```
```
[root@123 vecty]# go get -u github.com/iafan/goplayspace/...
# cd /root/Projects/golang/src/github.com/gopherjs/vecty; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> branch

package github.com/gopherjs/vecty: exit status 1
```
What am I doing wrong?

**Comment by zet4** [comment]
`-u` will update vecty's repo to newest, without the flag it seemed to run but i get a 404 page, but that might be related to something else entirely...

**Comment by linkerlin** [comment]
@veganexe I submit a PR for this problem.

**Comment by iafan** [comment]
This should have been fixed with https://github.com/iafan/goplayspace/commit/a174206bced07a8abc7b94d5f48e0c347c11db7b

**Comment by iambudi** [comment]
I still got this error
 
`../../iafan/goplayspace/client/component/app/app.go:93:16: cannot use a (type *Application) as type vecty.Component in argument to vecty.Rerender:
	*Application does not implement vecty.Component (wrong type for Render method)
		have Render() *vecty.HTML
		want Render() vecty.ComponentOrHTML`

**Comment by iafan** [comment]
@iambudi I updated the code in https://github.com/iafan/goplayspace/commit/0478ff49459eb64e5646f0cf8fb4c272f69ca2fb to reflect recent Vecty API changes. Should compile fine now.
