### ISSUE TITLE
Dropdown box text for theme is white on white for Dark and Space themes

### ISSUE THREAD

**Issue by kdar** [iafan/goplayspace#2]
![image](https://cloud.githubusercontent.com/assets/119919/26802273/e59ec91c-4a0d-11e7-98a3-e37bb2288ef2.png)

**Comment by kdar** [comment]
This is on Windows 7, Chrome Version 58.0.3029.110 (64-bit)

**Comment by iafan** [comment]
Thanks! Fixed & deployed (make sure to force-reload the page for CSS changes to be picked up).
