### ISSUE TITLE
Is it possible to provide some API so you could create a playground by passing in some code?

### ISSUE THREAD

**Issue by nikitavoloboev** [iafan/goplayspace#20]
I want to highlight some code in my text editor and make a link to a playground of it that I can share. Without me going to goplayspace first, pasting in text there, pressing share and then getting the link.

Is this possible to do?

**Comment by iafan** [comment]
This is the API: https://github.com/iafan/goplayspace/blob/master/server/server.go#L111

You do a POST request with your code selection as a payload, and the response body you get back represents the ID of the snippet that you can use to construct the URL to either Go Play Space or official Go Playground.

**Comment by nikitavoloboev** [comment]
Thank you. This works.
