### ISSUE TITLE
new gopherjs version error

### ISSUE THREAD

**Issue by robotamer** [iafan/goplayspace#28]
```
./build-client && ./build-server
cannot find package "github.com/gopherjs/vecty" in any of:
	/opt/go/src/github.com/gopherjs/vecty (from $GOROOT)
	/home/tamer/code/go/src/github.com/gopherjs/vecty (from $GOPATH)
```

**Comment by iafan** [comment]
It looks like you just don't have Vecty installed or have something misconfigured. What happens if you run `go get -u github.com/gopherjs/vecty`? Any errors? If this command yields no errors, try running `bin/build-client` again.

**Comment by robotamer** [comment]
Worked, Thanks, Sorry should have looked closer.
Great job!!!
